### ISSUE TITLE
[Q]results结果所属漏洞判断

### ISSUE THREAD

**Issue by duzhg56980** [fullwaywang/QlRules#2]
<img width="850" alt="image" src="https://github.com/fullwaywang/QlRules/assets/158979731/7c637752-b92e-4d7e-9c09-b67a2cd25613">
请教您一下，我这用openssl的规则扫描openssl3.0.0、3.1.0、3.2.0、master，出来了一些结果，这些结果是新漏洞还是已知漏洞呢？该如何判断

**Comment by fullwaywang** [comment]
这是见仁见智的。当前公开的规则集，虽然做了一些误报规则消除，但扫描检出也不可避免存在误报和有效新漏洞混杂，因为缺陷代码上下文成因等因素；但这部分误报应该不会太多，可以逐个根据原始漏洞成因和补丁与检出位置比对，人工判断工作量也可行。也许可以捡到一些新漏洞: )
